#!/bin/bash
#SBATCH --workdir=/scratch/ms/gb/ukc/scratchdir/
#SBATCH --mail-type=FAIL
#SBATCH --output=/home/ms/gb/ukc/slurm_output/slurm-%j.out
#SBATCH --error=/home/ms/gb/ukc/slurm_output/slurm-%j.err
#SBATCH --qos=long

export MARS_MULTITARGET_STRICT_FORMAT=1

WORK=$SCRATCHDIR
mkdir -p $WORK
if [ $? != 0 ]
  then
  echo "Could not make scratch directory so exiting!"
  exit
fi
cd $WORK

mars << eor
retrieve,
 class=ea,
 date=$DATE,
 expver=1,
 levtype=sfc,
 param=165.128/166.128/168.128/167.128/151.128/34.128/31.128/235.128/164.128/137.128,
 stream=enda,
 time=0/to/21/by/3,
 type=em,
 grid=0.25/0.25,
 format=netcdf,
 target="/scratch/ms/gb/ukc/era5_extract_pre_split/era5-s-en-mean-nc/ecmwf-era5_{stream}_{type}_{levtype}_[DATE][time].grb".
eor

export MARS_MULTITARGET_STRICT_FORMAT=1


V0='20220501/20220502/20220503/20220504/20220505/20220506/20220507/20220508/20220509/20220510/20220511/20220512/20220513/20220514/20220515/20220516/20220517/20220518/20220519/20220520/20220521/20220522/20220523/20220524/20220525/20220526/20220527/20220528/20220529/20220530/20220531'

for DATE in $V0
do

WORK=$SCRATCHDIR
mkdir -p $WORK
if [ $? != 0 ]
  then
  echo "Could not make scratch directory so exiting!"
  exit
fi
cd $WORK

mars << eor
retrieve,
 class=ea,
 date=$DATE,
 expver=1,
 levtype=sfc,
 param=165.128/166.128/168.128/167.128/151.128/34.128/31.128/235.128/164.128/137.128,
 stream=enda,
 time=0/to/21/by/3,
 type=em,
 grid=0.25/0.25,
 format=netcdf,
 target="/scratch/ms/gb/ukc/era5_extract_pre_split/era5-s-en-mean-nc/ecmwf-era5_{stream}_{type}_{levtype}_[DATE][time].grb".
eor

done
